web:
  build: .
  links:
   - db:db
  ports:
   - "9090:8080"
db:
 image: mysql:5.6
 environment:
   MYSQL_ROOT_PASSWORD: admin
 ports:
   - 3309:3306
 volumes:
   - ./db-dump:/docker-entrypoint-initdb.d
