version: '2'
services:
  haproxy:
    image: dockercloud/haproxy
    links:
      - web
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: .
    links:
     - db:db
    ports:
     - "8080"
  db:
   image: mysql:5.6
   environment:
     MYSQL_ROOT_PASSWORD: admin
   ports:
     - 3309:3306
   volumes:
     - ./db-dump:/docker-entrypoint-initdb.d
